
<?php


return [


    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'DashboardControllers@Dashboard' => 'list-dashboard',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'TopMenuControllers@index' => 'list-topMenus',
    'TopMenuControllers@edit' => 'edit-topMenu',
    'TopMenuControllers@update' => 'edit-topMenu',
    'TopMenuControllers@fastEdit' => 'edit-topMenu',
    'TopMenuControllers@add' => 'add-topMenu',
    'TopMenuControllers@create' => 'add-topMenu',
    'TopMenuControllers@delete' => 'delete-topMenu',
    'TopMenuControllers@arrange' => 'sort-topMenu',
    'TopMenuControllers@sort' => 'sort-topMenu',
    'TopMenuControllers@charts' => 'charts-topMenu',

    'BottomMenuControllers@index' => 'list-bottomMenus',
    'BottomMenuControllers@edit' => 'edit-bottomMenu',
    'BottomMenuControllers@update' => 'edit-bottomMenu',
    'BottomMenuControllers@add' => 'add-bottomMenu',
    'BottomMenuControllers@fastEdit' => 'edit-bottomMenu',
    'BottomMenuControllers@create' => 'add-bottomMenu',
    'BottomMenuControllers@delete' => 'delete-bottomMenu',
    'BottomMenuControllers@arrange' => 'sort-bottomMenu',
    'BottomMenuControllers@sort' => 'sort-bottomMenu',
    'BottomMenuControllers@charts' => 'charts-bottomMenu',

    'SideMenuControllers@index' => 'list-sideMenus',
    'SideMenuControllers@edit' => 'edit-sideMenu',
    'SideMenuControllers@update' => 'edit-sideMenu',
    'SideMenuControllers@add' => 'add-sideMenu',
    'SideMenuControllers@fastEdit' => 'edit-sideMenu',
    'SideMenuControllers@create' => 'add-sideMenu',
    'SideMenuControllers@delete' => 'delete-sideMenu',
    'SideMenuControllers@arrange' => 'sort-sideMenu',
    'SideMenuControllers@sort' => 'sort-sideMenu',
    'SideMenuControllers@charts' => 'charts-sideMenu',

    'AdvantageControllers@index' => 'list-advantages',
    'AdvantageControllers@edit' => 'edit-advantage',
    'AdvantageControllers@fastEdit' => 'edit-advantage',
    'AdvantageControllers@update' => 'edit-advantage',
    'AdvantageControllers@add' => 'add-advantage',
    'AdvantageControllers@create' => 'add-advantage',
    'AdvantageControllers@delete' => 'delete-advantage',
    'AdvantageControllers@arrange' => 'sort-advantage',
    'AdvantageControllers@sort' => 'sort-advantage',
    'AdvantageControllers@charts' => 'charts-advantage',

    'BenefitControllers@index' => 'list-benefits',
    'BenefitControllers@edit' => 'edit-benefit',
    'BenefitControllers@update' => 'edit-benefit',
    'BenefitControllers@fastEdit' => 'edit-benefit',
    'BenefitControllers@add' => 'add-benefit',
    'BenefitControllers@create' => 'add-benefit',
    'BenefitControllers@delete' => 'delete-benefit',
    'BenefitControllers@arrange' => 'sort-benefit',
    'BenefitControllers@sort' => 'sort-benefit',
    'BenefitControllers@charts' => 'charts-benefit',

    'CityControllers@index' => 'list-cities',
    'CityControllers@edit' => 'edit-city',
    'CityControllers@update' => 'edit-city',
    'CityControllers@fastEdit' => 'edit-city',
    'CityControllers@add' => 'add-city',
    'CityControllers@create' => 'add-city',
    'CityControllers@delete' => 'delete-city',
    'CityControllers@arrange' => 'sort-city',
    'CityControllers@sort' => 'sort-city',
    'CityControllers@charts' => 'charts-city',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    'PageControllers@arrange' => 'sort-page',
    'PageControllers@sort' => 'sort-page',
    'PageControllers@charts' => 'charts-page',
    'PageControllers@uploadImage' => 'uploadImage-page',
    'PageControllers@deleteImage' => 'deleteImage-page',

    'SliderControllers@index' => 'list-sliders',
    'SliderControllers@edit' => 'edit-slider',
    'SliderControllers@update' => 'edit-slider',
    'SliderControllers@fastEdit' => 'edit-slider',
    'SliderControllers@add' => 'add-slider',
    'SliderControllers@create' => 'add-slider',
    'SliderControllers@delete' => 'delete-slider',
    'SliderControllers@arrange' => 'sort-slider',
    'SliderControllers@sort' => 'sort-slider',
    'SliderControllers@charts' => 'charts-slider',
    'SliderControllers@uploadImage' => 'uploadImage-slider',
    'SliderControllers@deleteImage' => 'deleteImage-slider',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',
    'ContactUsControllers@charts' => 'charts-contactUs',

    'LogControllers@index' => 'list-logs',
    'LogControllers@fastEdit' => 'edit-log',
    'LogControllers@delete' => 'delete-log',
    'LogControllers@arrange' => 'sort-log',
    'LogControllers@sort' => 'sort-log',
    'LogControllers@charts' => 'charts-log',

    'BlockedUsersControllers@index' => 'list-blockedUsers',
    'BlockedUsersControllers@fastEdit' => 'edit-blockedUser',
    'BlockedUsersControllers@delete' => 'delete-blockedUser',
    'BlockedUsersControllers@arrange' => 'sort-blockedUser',
    'BlockedUsersControllers@sort' => 'sort-blockedUser',
    'BlockedUsersControllers@charts' => 'charts-blockedUser',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@panel' => 'list-variables2',
    'VariablesControllers@uploadImage' => 'edit-variable2',
    'VariablesControllers@deleteImage' => 'edit-variable2',

    


];
