
<?php


return [


    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'DashboardControllers@Dashboard' => 'list-dashboard',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@arrange' => 'sort-user',
    'UsersControllers@sort' => 'sort-user',
    'UsersControllers@charts' => 'charts-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',
    'GroupsControllers@arrange' => 'sort-group',
    'GroupsControllers@sort' => 'sort-group',
    'GroupsControllers@charts' => 'charts-group',

    'TopMenuControllers@index' => 'list-topMenus',
    'TopMenuControllers@edit' => 'edit-topMenu',
    'TopMenuControllers@update' => 'edit-topMenu',
    'TopMenuControllers@fastEdit' => 'edit-topMenu',
    'TopMenuControllers@add' => 'add-topMenu',
    'TopMenuControllers@create' => 'add-topMenu',
    'TopMenuControllers@delete' => 'delete-topMenu',
    'TopMenuControllers@arrange' => 'sort-topMenu',
    'TopMenuControllers@sort' => 'sort-topMenu',
    'TopMenuControllers@charts' => 'charts-topMenu',

    'BottomMenuControllers@index' => 'list-bottomMenus',
    'BottomMenuControllers@edit' => 'edit-bottomMenu',
    'BottomMenuControllers@update' => 'edit-bottomMenu',
    'BottomMenuControllers@add' => 'add-bottomMenu',
    'BottomMenuControllers@fastEdit' => 'edit-bottomMenu',
    'BottomMenuControllers@create' => 'add-bottomMenu',
    'BottomMenuControllers@delete' => 'delete-bottomMenu',
    'BottomMenuControllers@arrange' => 'sort-bottomMenu',
    'BottomMenuControllers@sort' => 'sort-bottomMenu',
    'BottomMenuControllers@charts' => 'charts-bottomMenu',

    'AdvantageControllers@index' => 'list-advantages',
    'AdvantageControllers@edit' => 'edit-advantage',
    'AdvantageControllers@fastEdit' => 'edit-advantage',
    'AdvantageControllers@update' => 'edit-advantage',
    'AdvantageControllers@add' => 'add-advantage',
    'AdvantageControllers@create' => 'add-advantage',
    'AdvantageControllers@delete' => 'delete-advantage',
    'AdvantageControllers@arrange' => 'sort-advantage',
    'AdvantageControllers@sort' => 'sort-advantage',
    'AdvantageControllers@charts' => 'charts-advantage',

    'BenefitControllers@index' => 'list-benefits',
    'BenefitControllers@edit' => 'edit-benefit',
    'BenefitControllers@update' => 'edit-benefit',
    'BenefitControllers@fastEdit' => 'edit-benefit',
    'BenefitControllers@add' => 'add-benefit',
    'BenefitControllers@create' => 'add-benefit',
    'BenefitControllers@delete' => 'delete-benefit',
    'BenefitControllers@arrange' => 'sort-benefit',
    'BenefitControllers@sort' => 'sort-benefit',
    'BenefitControllers@charts' => 'charts-benefit',

    'CityControllers@index' => 'list-cities',
    'CityControllers@edit' => 'edit-city',
    'CityControllers@update' => 'edit-city',
    'CityControllers@fastEdit' => 'edit-city',
    'CityControllers@add' => 'add-city',
    'CityControllers@create' => 'add-city',
    'CityControllers@delete' => 'delete-city',
    'CityControllers@arrange' => 'sort-city',
    'CityControllers@sort' => 'sort-city',
    'CityControllers@charts' => 'charts-city',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    'PageControllers@arrange' => 'sort-page',
    'PageControllers@sort' => 'sort-page',
    'PageControllers@charts' => 'charts-page',
    'PageControllers@uploadImage' => 'uploadImage-page',
    'PageControllers@deleteImage' => 'deleteImage-page',

    'SliderControllers@index' => 'list-sliders',
    'SliderControllers@edit' => 'edit-slider',
    'SliderControllers@update' => 'edit-slider',
    'SliderControllers@fastEdit' => 'edit-slider',
    'SliderControllers@add' => 'add-slider',
    'SliderControllers@create' => 'add-slider',
    'SliderControllers@delete' => 'delete-slider',
    'SliderControllers@arrange' => 'sort-slider',
    'SliderControllers@sort' => 'sort-slider',
    'SliderControllers@charts' => 'charts-slider',
    'SliderControllers@uploadImage' => 'uploadImage-slider',
    'SliderControllers@deleteImage' => 'deleteImage-slider',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',
    'ContactUsControllers@charts' => 'charts-contactUs',

    'LogControllers@index' => 'list-logs',
    'LogControllers@fastEdit' => 'edit-log',
    'LogControllers@delete' => 'delete-log',
    'LogControllers@arrange' => 'sort-log',
    'LogControllers@sort' => 'sort-log',
    'LogControllers@charts' => 'charts-log',

    'BlockedUsersControllers@index' => 'list-blockedUsers',
    'BlockedUsersControllers@fastEdit' => 'edit-blockedUser',
    'BlockedUsersControllers@delete' => 'delete-blockedUser',
    'BlockedUsersControllers@arrange' => 'sort-blockedUser',
    'BlockedUsersControllers@sort' => 'sort-blockedUser',
    'BlockedUsersControllers@charts' => 'charts-blockedUser',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@panel' => 'list-variables2',
    'VariablesControllers@uploadImage' => 'edit-variable2',
    'VariablesControllers@deleteImage' => 'edit-variable2',

    'SideMenuControllers@index' => 'list-sideMenus',
    'SideMenuControllers@edit' => 'edit-sideMenu',
    'SideMenuControllers@update' => 'edit-sideMenu',
    'SideMenuControllers@add' => 'add-sideMenu',
    'SideMenuControllers@fastEdit' => 'edit-sideMenu',
    'SideMenuControllers@create' => 'add-sideMenu',
    'SideMenuControllers@delete' => 'delete-sideMenu',
    'SideMenuControllers@arrange' => 'sort-sideMenu',
    'SideMenuControllers@sort' => 'sort-sideMenu',
    'SideMenuControllers@charts' => 'charts-sideMenu',

    'MembershipControllers@index' => 'list-memberships',
    'MembershipControllers@edit' => 'edit-membership',
    'MembershipControllers@update' => 'edit-membership',
    'MembershipControllers@fastEdit' => 'edit-membership',
    'MembershipControllers@add' => 'add-membership',
    'MembershipControllers@create' => 'add-membership',
    'MembershipControllers@delete' => 'delete-membership',
    'MembershipControllers@arrange' => 'sort-membership',
    'MembershipControllers@sort' => 'sort-membership',
    'MembershipControllers@charts' => 'charts-membership',
    'MembershipControllers@uploadImage' => 'uploadImage-membership',
    'MembershipControllers@deleteImage' => 'deleteImage-membership',

    'FeatureControllers@index' => 'list-features',
    'FeatureControllers@edit' => 'edit-feature',
    'FeatureControllers@update' => 'edit-feature',
    'FeatureControllers@fastEdit' => 'edit-feature',
    'FeatureControllers@add' => 'add-feature',
    'FeatureControllers@create' => 'add-feature',
    'FeatureControllers@delete' => 'delete-feature',
    'FeatureControllers@arrange' => 'sort-feature',
    'FeatureControllers@sort' => 'sort-feature',
    'FeatureControllers@charts' => 'charts-feature',

    'TargetGroupControllers@index' => 'list-targets',
    'TargetGroupControllers@edit' => 'edit-target',
    'TargetGroupControllers@update' => 'edit-target',
    'TargetGroupControllers@fastEdit' => 'edit-target',
    'TargetGroupControllers@add' => 'add-target',
    'TargetGroupControllers@create' => 'add-target',
    'TargetGroupControllers@delete' => 'delete-target',
    'TargetGroupControllers@arrange' => 'sort-target',
    'TargetGroupControllers@sort' => 'sort-target',
    'TargetGroupControllers@charts' => 'charts-target',

    'OrderCategoryControllers@index' => 'list-order-categories',
    'OrderCategoryControllers@edit' => 'edit-order-category',
    'OrderCategoryControllers@update' => 'edit-order-category',
    'OrderCategoryControllers@fastEdit' => 'edit-order-category',
    'OrderCategoryControllers@add' => 'add-order-category',
    'OrderCategoryControllers@create' => 'add-order-category',
    'OrderCategoryControllers@delete' => 'delete-order-category',
    'OrderCategoryControllers@arrange' => 'sort-order-category',
    'OrderCategoryControllers@sort' => 'sort-order-category',
    'OrderCategoryControllers@charts' => 'charts-order-category',

    'OrderControllers@index' => 'list-orders',
    'OrderControllers@softDelete' => 'delete-order',
    'OrderControllers@delete' => 'delete-order',
    'OrderControllers@fastEdit' => 'edit-order',
    'OrderControllers@changeStatus' => 'edit-order',
    'OrderControllers@charts' => 'charts-order',

    'ProjectControllers@index' => 'list-projects',
    'ProjectControllers@edit' => 'edit-project',
    'ProjectControllers@update' => 'edit-project',
    'ProjectControllers@fastEdit' => 'edit-project',
    'ProjectControllers@add' => 'add-project',
    'ProjectControllers@create' => 'add-project',
    'ProjectControllers@delete' => 'delete-project',
    'ProjectControllers@arrange' => 'sort-project',
    'ProjectControllers@sort' => 'sort-project',
    'ProjectControllers@charts' => 'charts-project',
    'ProjectControllers@uploadImage' => 'uploadImage-project',
    'ProjectControllers@deleteImage' => 'deleteImage-project',
    'ProjectControllers@deleteImages' => 'deleteImage-project',

    'ProjectCategoryControllers@index' => 'list-project-categories',
    'ProjectCategoryControllers@edit' => 'edit-project-category',
    'ProjectCategoryControllers@update' => 'edit-project-category',
    'ProjectCategoryControllers@fastEdit' => 'edit-project-category',
    'ProjectCategoryControllers@add' => 'add-project-category',
    'ProjectCategoryControllers@create' => 'add-project-category',
    'ProjectCategoryControllers@delete' => 'delete-project-category',
    'ProjectCategoryControllers@arrange' => 'sort-project-category',
    'ProjectCategoryControllers@sort' => 'sort-project-category',
    'ProjectCategoryControllers@charts' => 'charts-project-category',

    'CouponControllers@index' => 'list-coupons',
    'CouponControllers@edit' => 'edit-coupon',
    'CouponControllers@update' => 'edit-coupon',
    'CouponControllers@fastEdit' => 'edit-coupon',
    'CouponControllers@add' => 'add-coupon',
    'CouponControllers@create' => 'add-coupon',
    'CouponControllers@delete' => 'delete-coupon',
    'CouponControllers@arrange' => 'sort-coupon',
    'CouponControllers@sort' => 'sort-coupon',
    'CouponControllers@charts' => 'charts-coupon',

    'BlogCategoryControllers@index' => 'list-blog-categories',
    'BlogCategoryControllers@edit' => 'edit-blog-category',
    'BlogCategoryControllers@update' => 'edit-blog-category',
    'BlogCategoryControllers@fastEdit' => 'edit-blog-category',
    'BlogCategoryControllers@add' => 'add-blog-category',
    'BlogCategoryControllers@create' => 'add-blog-category',
    'BlogCategoryControllers@delete' => 'delete-blog-category',
    'BlogCategoryControllers@arrange' => 'sort-blog-category',
    'BlogCategoryControllers@sort' => 'sort-blog-category',
    'BlogCategoryControllers@charts' => 'charts-blog-category',

    'BlogControllers@index' => 'list-blogs',
    'BlogControllers@edit' => 'edit-blog',
    'BlogControllers@update' => 'edit-blog',
    'BlogControllers@fastEdit' => 'edit-blog',
    'BlogControllers@add' => 'add-blog',
    'BlogControllers@create' => 'add-blog',
    'BlogControllers@delete' => 'delete-blog',
    'BlogControllers@arrange' => 'sort-blog',
    'BlogControllers@sort' => 'sort-blog',
    'BlogControllers@charts' => 'charts-blog',
    'BlogControllers@uploadImage' => 'uploadImage-blog',
    'BlogControllers@deleteImage' => 'deleteImage-blog',
    
    'UserCardControllers@index' => 'list-user-cards',
    'UserCardControllers@edit' => 'edit-user-card',
    'UserCardControllers@update' => 'edit-user-card',
    'UserCardControllers@fastEdit' => 'edit-user-card',
    'UserCardControllers@add' => 'add-user-card',
    'UserCardControllers@create' => 'add-user-card',
    'UserCardControllers@delete' => 'delete-user-card',
    'UserCardControllers@arrange' => 'sort-user-card',
    'UserCardControllers@sort' => 'sort-user-card',
    'UserCardControllers@charts' => 'charts-user-card',

    'UserRequestControllers@index' => 'list-user-requests',
    'UserRequestControllers@softDelete' => 'delete-user-request',
    'UserRequestControllers@delete' => 'delete-user-request',
    'UserRequestControllers@fastEdit' => 'edit-user-request',
    'UserRequestControllers@charts' => 'charts-user-request',

    'CardPromotionsControllers@index' => 'list-card-promotions',
    'CardPromotionsControllers@softDelete' => 'delete-card-promotion',
    'CardPromotionsControllers@delete' => 'delete-card-promotion',
    'CardPromotionsControllers@fastEdit' => 'edit-card-promotion',
    'CardPromotionsControllers@charts' => 'charts-card-promotion',

    'UserCertificateControllers@index' => 'list-user-certificates',
    'UserCertificateControllers@download' => 'download-user-certificate',

    'UserMemberControllers@index' => 'list-user-members',
    'UserMemberControllers@edit' => 'edit-user-member',
    'UserMemberControllers@update' => 'edit-user-member',
    'UserMemberControllers@fastEdit' => 'edit-user-member',
    'UserMemberControllers@add' => 'add-user-member',
    'UserMemberControllers@create' => 'add-user-member',
    'UserMemberControllers@delete' => 'delete-user-member',
    'UserMemberControllers@arrange' => 'sort-user-member',
    'UserMemberControllers@sort' => 'sort-user-member',
    'UserMemberControllers@charts' => 'charts-user-member',

];
